name: Diff check bun lockfile

on: push

jobs:
  diff-check:
    name: Diff check bun lockfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up github
        run: |
          touch .gitattributes && echo "bun.lockb diff=lockb" > .gitattributes
          git config diff.lockb.textconv bun
          git config diff.lockb.binary true
      - uses: oven-sh/setup-bun@v1
      - name: diff check main
        run: git diff HEAD origin/main -- bun.lockb
